# File: azure-pipelines.yml
trigger:
- main
pool:
  vmImage: 'windows-latest'
variables:
  DB_name: $(DBName)
stages:
- stage: PublishToAzureSQL
  jobs:
  - job: PublishToAzureSQLDevelopment
    steps:
    - checkout: self
      persistCredentials: true
    
    - task: AzurePowerShell@5
      displayName: 'Run SQL queries'
      env:
        MAPPED_DBLogin: $(DBLogin)
        MAPPED_DBServer: $(DBServer)
        MAPPED_PW: $(password)
      inputs:
        azureSubscription: 'Connect Azure SQL DB with Azure DevOps' 
        ScriptType: InlineScript
        Inline: |
          Write-Host "Query from the Azure SQL"
          Write-Host "The database is: " + $(DBLogin)
          $query_output = Invoke-sqlcmd -ConnectionString "Server=$env:MAPPED_DBServer;Initial Catalog=$env:DB_name;Persist Security Info=False;User ID=$env:MAPPED_DBLogin;Password= $env:MAPPED_PW;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30" -Query "select * from dbo.characters"
          $query_output | Out-File $env:BUILD_SOURCESDIRECTORY/query_output.txt
          $git_merge_output = git log -m --name-only -n 1
          $git_merge_output | Out-File $env:BUILD_SOURCESDIRECTORY/git_merge_output.txt
        azurePowerShellVersion: LatestVersion
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: buildresult