# File: azure-pipelines.yml
trigger:
- main
pool:
  vmImage: 'windows-latest'
variables:
  DB_name: $(DB)
stages:
- stage: PublishToAzureSQL
  jobs:
  - job: PublishToAzureSQLDevelopment
    steps:
    - checkout: none
    
    - task: AzurePowerShell@5
      displayName: 'Run SQL queries'
      env:
        MAPPED_DB: $(DB)
      inputs:
        azureSubscription: 'Connect Azure SQL DB with Azure DevOps' 
        ScriptType: InlineScript
        Inline: |
          $result = Invoke-sqlcmd -ConnectionString "Data Source=$SQLserver;Initial Catalog=$DB;User Id=$DBLogin;Password=$DBPW" -Query "select * from dbo.characters"
          Write-Host $result
        azurePowerShellVersion: LatestVersion