# File: azure-pipelines.yml
trigger:
- main
pool:
  vmImage: 'windows-latest'

stages:
- stage: PublishToAzureSQL
  jobs:
  - job: PublishToAzureSQLDevelopment
    steps:
    - checkout: none
    
    - task: AzurePowerShell@5
      displayName: 'Run SQL queries'
      inputs:
        azureSubscription: 'Connect Azure SQL DB with Azure DevOps' 
        ScriptType: InlineScript
        Inline: |
          $SQLserver = $(SQLserver)
          $DB = $(DB)
          $Login = $(DBLogin)
          $PW = $(DBPW)
          $result = Invoke-sqlcmd -ConnectionString "Data Source=$SQLserver;Initial Catalog=$DB;User Id=$Login;Password=$PW" -Query "select * from dbo.characters"
          Write-Host $result
        azurePowerShellVersion: LatestVersion