# File: azure-pipelines.yml
trigger:
- main
steps:
- task: PowerShell@2
  displayName: Set up database and schedule
  inputs:
    targetType: 'inline'
    script: |
      
      $serverName = "localhost\sqlexpress"
      $databaseName = "Movies"      
      $tableName = "characters"
      $connectionString ="Server=$serverName;Database=$databaseName;Trusted_Connection=True;IntegratedSecurity=True;Encrypt=false;TrustServerCertificate=true"      $schemaName = "Characters"
      $sqlCommand = "INSERT INTO $schemaName.$tableName(char_id, first_name, last_name)
      VALUES (4, 'Rabeus', 'Hadgrid');"
      $result=Invoke-SqlCmd -ConnectionString $connectionString -Query $sqlCommand
      if($LASTEXITCODE -ne 0){Write-Host "##[task.logissue type=error] SQL command failed!" exit 1} else {Write-Host "The record is inserted successfully!"}
    


