# File: azure-pipelines.yml
trigger:
- main
pool:
  vmImage: 'windows-latest'
variables:
  DB_name: $(DB)
stages:
- stage: PublishToAzureSQL
  jobs:
  - job: PublishToAzureSQLDevelopment
    steps:
    - checkout: none
    
    - task: AzurePowerShell@5
      displayName: 'Run SQL queries'
      env:
        MAPPED_DB: $(DB)
      inputs:
        azureSubscription: 'Connect Azure SQL DB with Azure DevOps' 
        ScriptType: InlineScript
        Inline: |
          Write-Host $(DBLogin)
          $result = Invoke-sqlcmd -ConnectionString "Server=tcp:cprose-sql-movies.database.windows.net,1433;Initial Catalog=FirstDatabase;Persist Security Info=False;User ID=CloudSAdeb1ce11;Password=$(DBPW);MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30" -Query "select * from dbo.characters"
          Write-Host $result
        azurePowerShellVersion: LatestVersion