# File: azure-pipelines.yml
trigger:
- main
pool:
  vmImage: 'windows-latest'
variables:
  DB_name: $(DB)
stages:
- stage: PublishToAzureSQL
  jobs:
  - job: PublishToAzureSQLDevelopment
    steps:
    - checkout: none
    
    - task: AzurePowerShell@5
      displayName: 'Run SQL queries'
      env:
        MAPPED_DBLogin: $(DBLogin)
        MAPPED_DBServer: $(DBServer)
        MAPPED_PW: $(password)
      inputs:
        azureSubscription: 'Connect Azure SQL DB with Azure DevOps' 
        ScriptType: InlineScript
        Inline: |
          Write-Host $(DBLogin)
          $output = Invoke-sqlcmd -ConnectionString "Server=$env:MAPPED_DBServer;Initial Catalog=DB_name;Persist Security Info=False;User ID=$env:MAPPED_DBLogin;Password= $env:MAPPED_PW;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30" -Query "select * from dbo.characters"
          $output | Out-File -FilePath .\output.txt
        azurePowerShellVersion: LatestVersion