# File: azure-pipelines.yml
trigger:
- main
steps:
- task: PowerShell@2
  displayName: Set up database and schedule
  inputs:
    targetType: 'inline'
    script: |
      
      $serverName = "localhost\sqlexpress"
      $databaseName = "Movies"      
      $tableName = "characters"
      $schemaName = "dbo"
      $connectionString ="Server=$serverName;Database=$databaseName;Trusted_Connection=True;IntegratedSecurity=True;Encrypt=false;TrustServerCertificate=true"
      $sqlScript="INSERT INTO $schemaName.$tableName(char_id, last_name, first_name) VALUES (4, 'Rabeus', 'Hadgrid');"
      try {
        Invoke-SqlCmd -ConnectionString $connectionString -Query $sqlScript
        Write-Host "Successfully executed script: $scriptName"
      } catch {
        Write-Error "Error executing script: $scriptName - $($_.Exception.Message)"
      }
      