# File: azure-pipelines.yml
trigger:
- main
pool:
  vmImage: 'windows-latest'
stages:
- stage: PublishToAzureSQL
  jobs:
  - job: PublishToAzureSQLDevelopment
    steps:
    - checkout: none
    
    - task: AzurePowerShell@5
      displayName: 'Run SQL queries'
      inputs:
        azureSubscription: 'Connect Azure SQL DB with Azure DevOps' 
        ScriptType: InlineScript
        Inline: |
          $SQLserver = "cprose-sql-movies.database.windows.net"
          $DB = "FirstDatabase"
          $result = Invoke-sqlcmd -ServerInstance $SQLserver -Database $DB -Query "select * from dbo.characters"
          Write-Host $result
        azurePowerShellVersion: LatestVersion