# File: azure-pipelines.yml
trigger:
- main
pool:
  vmImage: 'windows-latest'
variables:
  DB_name: $(DBName)
stages:
- stage: PublishToAzureSQL
  jobs:
  - job: PublishToAzureSQLDevelopment
    steps:
    - checkout: self
      persistCredentials: true
    

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
         Write-Host "Query from the Azure SQL"
         Write-Host $(DBLogin)
         $query_output = Invoke-sqlcmd -ConnectionString "Server=cprose-sql-movies;Initial Catalog=FirstDatabase;Persist Security Info=False;User ID=CloudSAdeb1ce11;Password= UnlockDatabase@135#;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30" -Query "select * from dbo.characters"
         $query_output | Out-File $env:BUILD_SOURCESDIRECTORY/query_output.txt
         $git_merge_output = git log -m --name-only -n 1
         $git_merge_output | Out-File $env:BUILD_SOURCESDIRECTORY/git_merge_output.txt

    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: buildresult